import { 
  Brain, Calendar, Trophy, Users, Video, Sparkles, 
  GraduationCap, FileText, Book, Award, LayoutTemplate 
} from "lucide-react";

export interface TemplateType {
  id: string;
  title: string;
  type: string;
  style: string;
  scene: string;
  hot: number;
  time: string;
  colorBg: string;
  tagText: string;
  hasPrize: boolean;
  percentage: number;
  stats: { conversions: string; participants: string; difficulty: string };
  chartData: number[];
}

export const CATEGORY_CONFIGS: Record<string, {
  bannerTitle: string;
  bannerDesc: string;
  subPlaystyles: string[];
  bannerColor: string;
}> = {
  "知识答题": {
    bannerTitle: "知识答题专区",
    bannerDesc: "脑力狂欢，科学知识、社情民意、行业规章大比拼！支持秒级响应题目生成与答题等级证书荣誉颁发限制。",
    subPlaystyles: ["全部", "百科问答", "科普知识", "文史常识", "智力开发", "生活常识"],
    bannerColor: "from-blue-500/10 to-indigo-500/10 border-blue-100 text-blue-900"
  },
  "每日一答": {
    bannerTitle: "每日一答专区",
    bannerDesc: "每日打卡，长期培养用户习惯！融合积分、金币及签到奖励，深度唤醒沉睡粉丝促活留存。",
    subPlaystyles: ["全部", "每日打卡", "签到赢奖", "单词打卡", "趣味问答", "理财早班车"],
    bannerColor: "from-amber-500/10 to-yellow-600/10 border-yellow-100 text-amber-900"
  },
  "闯关答题": {
    bannerTitle: "闯关答题专区",
    bannerDesc: "成就攀升，通关大闯关！极具仪式感的递进关卡，内置游戏化音效，极大提升答完率与留存周期。",
    subPlaystyles: ["全部", "安全闯关", "传统古语", "成语高手", "常识大赛", "极速升级"],
    bannerColor: "from-purple-500/10 to-fuchsia-600/10 border-fuchsia-100 text-fuchsia-900"
  },
  "PK答题": {
    bannerTitle: "PK答题专区",
    bannerDesc: "热血智斗，匹配PK比脑力！实时段位排名或者双人好友局，裂变速度快，互动极其频繁。",
    subPlaystyles: ["全部", "王者对决", "排位挑战", "默契测试", "群英激斗", "情侣测试"],
    bannerColor: "from-rose-500/10 to-pink-650/10 border-pink-100 text-pink-900"
  },
  "视频答题": {
    bannerTitle: "视频答题专区",
    bannerDesc: "视听联动，情景模拟沉浸式演练！突破传统纯文字限制，寓教于乐，极大提升安全教育和品牌营销效果。",
    subPlaystyles: ["全部", "看片答题", "情景还原", "安全教学", "名场面还原", "视听演练"],
    bannerColor: "from-violet-500/10 to-indigo-500/10 border-indigo-100 text-indigo-900"
  },
  "趣味答题": {
    bannerTitle: "趣味答题专区",
    bannerDesc: "测一测你最契合哪种超级身份？朋友圈现象级裂变源泉，轻松捕获千万级传播曝光和裂变引流。",
    subPlaystyles: ["全部", "性格测试", "命运罗盘", "星座运势", "神仙体质", "穿越时空"],
    bannerColor: "from-emerald-500/10 to-teal-500/10 border-teal-100 text-teal-900"
  },
  "学习答题": {
    bannerTitle: "学习答题专区",
    bannerDesc: "学练一体，以答带学！包含新员工培训、新政策宣贯等商务场景，提供详细解析机制，轻量化学习神器。",
    subPlaystyles: ["全部", "入职通关", "核心条令", "常识提分", "英语精炼", "行测特训"],
    bannerColor: "from-cyan-500/10 to-blue-600/10 border-blue-100 text-blue-900"
  },
  "练习": {
    bannerTitle: "练习训练专区",
    bannerDesc: "错题精炼，智能批改，支持自主刷题！可关联个人云错题本，模拟实际场景进行答题演练。",
    subPlaystyles: ["全部", "驾校考试", "常识训练", "周练测试", "模拟真题", "专项提分"],
    bannerColor: "from-slate-500/10 to-slate-700/10 border-slate-100 text-slate-900"
  },
  "考试": {
    bannerTitle: "正规大考专区",
    bannerDesc: "高规格在线考试，人脸认证及防作弊机制，严格限时交卷！支持生成官方电子认证证书体系。",
    subPlaystyles: ["全部", "卓越员工", "消防大考", "知识竞赛", "安全生产", "年度大考"],
    bannerColor: "from-red-500/10 to-red-650/10 border-red-100 text-red-900"
  },
  "课程": {
    bannerTitle: "课程答题专区",
    bannerDesc: "微课精讲视频配合课后选择题！完整课时管理，助力知识体系沉淀、全员综合素质系统性跃迁。",
    subPlaystyles: ["全部", "小白进阶", "编程实战", "AI核心课", "新媒体运营", "技能认证"],
    bannerColor: "from-pink-500/10 to-rose-500/10 border-rose-100 text-rose-800"
  }
};

export const QUIZ_CATEGORIES = [
  { 
    id: "全部", 
    name: "精选推荐", 
    count: 85, 
    desc: "爆款答题玩法推荐", 
    bg: "from-blue-50/90 to-white", 
    color: "text-blue-700", 
    subColor: "text-blue-500/85",
    activeBg: "bg-blue-600",
    activeTextColor: "text-white",
    activeSubColor: "text-blue-100",
    fillColor: "#2563eb",
    icon: LayoutTemplate
  },
  { 
    id: "知识答题", 
    name: "知识答题", 
    count: 42, 
    desc: "脑力大碰撞", 
    bg: "from-blue-50/80 to-white", 
    color: "text-sky-700", 
    subColor: "text-sky-500/85",
    activeBg: "bg-sky-600",
    activeTextColor: "text-white",
    activeSubColor: "text-sky-100",
    fillColor: "#0284c7",
    icon: Brain
  },
  { 
    id: "每日一答", 
    name: "每日一答", 
    count: 28, 
    desc: "培养用户打卡习惯", 
    bg: "from-amber-50/90 to-white", 
    color: "text-amber-700", 
    subColor: "text-amber-500/85",
    activeBg: "bg-amber-600",
    activeTextColor: "text-white",
    activeSubColor: "text-amber-100",
    fillColor: "#d97706",
    icon: Calendar
  },
  { 
    id: "闯关答题", 
    name: "闯关答题", 
    count: 36, 
    desc: "通阶挑战高能留存", 
    bg: "from-purple-50/90 to-white", 
    color: "text-purple-700", 
    subColor: "text-purple-500/85",
    activeBg: "bg-purple-600",
    activeTextColor: "text-white",
    activeSubColor: "text-purple-100",
    fillColor: "#9333ea",
    icon: Trophy
  },
  { 
    id: "PK答题", 
    name: "PK答题", 
    count: 39, 
    desc: "实时匹配互邀挑战", 
    bg: "from-rose-50/90 to-white", 
    color: "text-rose-700", 
    subColor: "text-rose-500/85",
    activeBg: "bg-[#db2777]",
    activeTextColor: "text-white",
    activeSubColor: "text-pink-100",
    fillColor: "#db2777",
    icon: Users
  },
  { 
    id: "视频答题", 
    name: "视频答题", 
    count: 24, 
    desc: "全景视频真切还原", 
    bg: "from-violet-50/90 to-white", 
    color: "text-violet-700", 
    subColor: "text-violet-500/85",
    activeBg: "bg-violet-600",
    activeTextColor: "text-white",
    activeSubColor: "text-indigo-100",
    fillColor: "#4f46e5",
    icon: Video
  },
  { 
    id: "趣味答题", 
    name: "趣味答题", 
    count: 55, 
    desc: "测试裂变轻松刷屏", 
    bg: "from-emerald-50/90 to-white", 
    color: "text-emerald-700", 
    subColor: "text-emerald-500/85",
    activeBg: "bg-emerald-600",
    activeTextColor: "text-white",
    activeSubColor: "text-emerald-100",
    fillColor: "#059669",
    icon: Sparkles
  },
  { 
    id: "学习答题", 
    name: "学习答题", 
    count: 30, 
    desc: "学练并济政策宣贯", 
    bg: "from-cyan-50/90 to-white", 
    color: "text-cyan-700", 
    subColor: "text-cyan-500/85",
    activeBg: "bg-cyan-600",
    activeTextColor: "text-white",
    activeSubColor: "text-cyan-100",
    fillColor: "#0891b2",
    icon: GraduationCap
  },
  { 
    id: "练习", 
    name: "练习", 
    count: 45, 
    desc: "专项题库错题精练", 
    bg: "from-slate-50/90 to-white", 
    color: "text-slate-700", 
    subColor: "text-slate-500/85",
    activeBg: "bg-slate-755",
    activeTextColor: "text-white",
    activeSubColor: "text-slate-200",
    fillColor: "#475569",
    icon: FileText
  },
  { 
    id: "考试", 
    name: "考试", 
    count: 21, 
    desc: "防作弊严格认证大考", 
    bg: "from-red-50/90 to-white", 
    color: "text-red-700", 
    subColor: "text-red-500/85",
    activeBg: "bg-red-600",
    activeTextColor: "text-white",
    activeSubColor: "text-red-100",
    fillColor: "#dc2626",
    icon: Award
  },
  { 
    id: "课程", 
    name: "课程", 
    count: 18, 
    desc: "微课体系附带随堂练", 
    bg: "from-pink-50/90 to-white", 
    color: "text-pink-700", 
    subColor: "text-pink-500/85",
    activeBg: "bg-pink-600",
    activeTextColor: "text-white",
    activeSubColor: "text-pink-100",
    fillColor: "#ec4899",
    icon: Book
  }
];

export const TEMPLATES_DATA: TemplateType[] = [
  {
    id: "q1",
    title: "高考百科知识大PK",
    type: "知识答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 42100,
    time: "2026-05-18",
    colorBg: "from-[#111827] via-[#1E1B4B] to-[#311042]",
    tagText: "高能比拼 题王争霸",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "6.9%", participants: "154k", difficulty: "★★★" },
    chartData: [40, 55, 75, 90, 98]
  },
  {
    id: "q2",
    title: "每日单词打卡挑战赛",
    type: "每日一答",
    style: "简约",
    scene: "每日打卡",
    hot: 32050,
    time: "2026-05-10",
    colorBg: "from-[#450A0A] via-[#7F1D1D] to-[#991B1B]",
    tagText: "习惯养成 兑奖激发",
    hasPrize: true,
    percentage: 94,
    stats: { conversions: "5.4%", participants: "108k", difficulty: "★☆☆" },
    chartData: [30, 50, 65, 80, 94]
  },
  {
    id: "q3",
    title: "企业安全生产规章大闯关",
    type: "闯关答题",
    style: "商务",
    scene: "企业级",
    hot: 28900,
    time: "2026-05-20",
    colorBg: "from-[#022C22] via-[#064E3B] to-[#047857]",
    tagText: "多维过关 警钟常鸣",
    hasPrize: false,
    percentage: 92,
    stats: { conversions: "4.8%", participants: "89k", difficulty: "★★☆" },
    chartData: [40, 60, 75, 85, 92]
  },
  {
    id: "q4",
    title: "王者答题热血排位赛",
    type: "PK答题",
    style: "卡通",
    scene: "趣味裂变",
    hot: 49400,
    time: "2026-05-22",
    colorBg: "from-[#0F172A] via-[#1E3A8A] to-[#1D4ED8]",
    tagText: "实时PK 智胜群雄",
    hasPrize: true,
    percentage: 99,
    stats: { conversions: "8.1%", participants: "210k", difficulty: "★★★" },
    chartData: [50, 70, 85, 95, 99]
  },
  {
    id: "q5",
    title: "安全出行规范视频答题",
    type: "视频答题",
    style: "可爱",
    scene: "附带解析",
    hot: 18400,
    time: "2026-05-02",
    colorBg: "from-[#111827] via-[#5C21B6] to-[#7C3AED]",
    tagText: "情境演练 视听联动",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.7%", participants: "45k", difficulty: "★★☆" },
    chartData: [35, 45, 60, 75, 86]
  },
  {
    id: "q6",
    title: "你的神仙体质趣味测评",
    type: "趣味答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 55200,
    time: "2026-05-25",
    colorBg: "from-[#0F172A] via-[#581C87] to-[#7E22CE]",
    tagText: "爆款刷屏 梦境测试",
    hasPrize: false,
    percentage: 97,
    stats: { conversions: "9.2%", participants: "340k", difficulty: "★☆☆" },
    chartData: [60, 75, 85, 94, 97]
  },
  {
    id: "q7",
    title: "入职培训企业文化通关",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 21500,
    time: "2026-04-18",
    colorBg: "from-[#0F172A] via-[#334155] to-[#475569]",
    tagText: "以学带答 快速融入",
    hasPrize: false,
    percentage: 89,
    stats: { conversions: "4.1%", participants: "59k", difficulty: "★☆☆" },
    chartData: [30, 45, 60, 78, 89]
  },
  {
    id: "q8",
    title: "行测常识高频考点训练",
    type: "练习",
    style: "简约",
    scene: "附带解析",
    hot: 23400,
    time: "2026-05-15",
    colorBg: "from-[#020617] via-[#0F172A] to-[#1E3A8A]",
    tagText: "错题精练 深度点拨",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "5.1%", participants: "92k", difficulty: "★★☆" },
    chartData: [45, 60, 70, 85, 91]
  },
  {
    id: "q9",
    title: "员工行为章程合规半年度大考",
    type: "考试",
    style: "商务",
    scene: "防作弊",
    hot: 15600,
    time: "2026-05-01",
    colorBg: "from-[#1E3A8A] via-[#0D9488] to-[#115E59]",
    tagText: "人脸实名 规避舞弊",
    hasPrize: true,
    percentage: 84,
    stats: { conversions: "3.2%", participants: "31k", difficulty: "★★★" },
    chartData: [20, 40, 55, 75, 84]
  },
  {
    id: "q10",
    title: "Python核心数据结构与AI实战",
    type: "课程",
    style: "科技",
    scene: "荣誉证书",
    hot: 27500,
    time: "2026-05-12",
    colorBg: "from-[#064E3B] via-[#047857] to-[#0D9488]",
    tagText: "边学边练 一键结课",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.9%", participants: "78k", difficulty: "★★★" },
    chartData: [40, 55, 75, 88, 95]
  },
  {
    id: "q11",
    title: "消防安全规范全国大测试",
    type: "考试",
    style: "简约",
    scene: "荣誉证书",
    hot: 31200,
    time: "2026-05-14",
    colorBg: "from-[#7F1D1D] via-[#B91C1C] to-[#ea580c]",
    tagText: "官方权威 答题认证",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "6.3%", participants: "128k", difficulty: "★★☆" },
    chartData: [40, 60, 78, 88, 96]
  },
  {
    id: "q12",
    title: "新媒体卓越运营精讲微课",
    type: "课程",
    style: "简约",
    scene: "企业级",
    hot: 19800,
    time: "2026-04-25",
    colorBg: "from-[#0F172A] via-[#1E1B4B] to-[#4F46E5]",
    tagText: "知识大课堂 随堂测验",
    hasPrize: false,
    percentage: 88,
    stats: { conversions: "4.2%", participants: "64k", difficulty: "★☆☆" },
    chartData: [25, 45, 60, 75, 88]
  },
  {
    id: "q13",
    title: "国家级文史经典与古诗名篇知识赛",
    type: "知识答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 31200,
    time: "2026-05-14",
    colorBg: "from-[#111827] via-[#5B21B6] to-[#7C3AED]",
    tagText: "弘扬经典 国学争霸",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "6.3%", participants: "128k", difficulty: "★★☆" },
    chartData: [40, 60, 78, 88, 96]
  },
  {
    id: "q14",
    title: "中国地理奥秘与世界之最百科趣味答题",
    type: "知识答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 28400,
    time: "2026-05-18",
    colorBg: "from-[#0F172A] via-[#1B1E4B] to-[#1E3A8A]",
    tagText: "探索世界 揽胜寰宇",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "5.8%", participants: "52k", difficulty: "★☆☆" },
    chartData: [40, 55, 78, 85, 91]
  },
  {
    id: "q15",
    title: "唐诗宋词名篇赏析与少年脑力会战",
    type: "知识答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 45600,
    time: "2026-05-24",
    colorBg: "from-[#450A0A] via-[#7F1D1D] to-[#B91C1C]",
    tagText: "腹有诗书 吟风咏月",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "8.7%", participants: "180k", difficulty: "★★☆" },
    chartData: [35, 60, 80, 92, 98]
  },
  {
    id: "q16",
    title: "少儿智力启蒙与科学基础百科冲关",
    type: "知识答题",
    style: "卡通",
    scene: "荣誉证书",
    hot: 31200,
    time: "2026-05-21",
    colorBg: "from-[#FAF5FF] via-[#F3E8FF] to-[#D946EF]",
    tagText: "快乐学习 探索求真",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "4.9%", participants: "74k", difficulty: "★☆☆" },
    chartData: [30, 45, 65, 82, 92]
  },
  {
    id: "q17",
    title: "地球生态保护与低碳节能科普评比",
    type: "知识答题",
    style: "简约",
    scene: "附带解析",
    hot: 39500,
    time: "2026-05-15",
    colorBg: "from-[#022C22] via-[#064E3B] to-[#10B981]",
    tagText: "指尖低碳 绿色低碳",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "7.1%", participants: "115k", difficulty: "★★☆" },
    chartData: [45, 60, 78, 89, 96]
  },
  {
    id: "q18",
    title: "世界名著与中外文学常识趣味竞玩",
    type: "知识答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 29800,
    time: "2026-05-17",
    colorBg: "from-[#111827] via-[#1E293B] to-[#3B82F6]",
    tagText: "品读经典 充实心灵",
    hasPrize: true,
    percentage: 94,
    stats: { conversions: "5.5%", participants: "82k", difficulty: "★★☆" },
    chartData: [30, 50, 72, 85, 94]
  },
  {
    id: "q19",
    title: "数理思维逻辑训练高难度脑力飞跃",
    type: "知识答题",
    style: "科技",
    scene: "附带解析",
    hot: 43200,
    time: "2026-05-25",
    colorBg: "from-[#0F172A] via-[#1E3A8A] to-[#2563EB]",
    tagText: "思维风暴 降维打击",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "8.1%", participants: "160k", difficulty: "★★★" },
    chartData: [40, 60, 78, 90, 98]
  },
  {
    id: "q20",
    title: "核心国学典籍与儒家章程合规复赛",
    type: "知识答题",
    style: "国潮",
    scene: "企业级",
    hot: 51200,
    time: "2026-05-26",
    colorBg: "from-[#450A0A] via-[#5C21B6] to-[#7C3AED]",
    tagText: "大音希声 儒道博大",
    hasPrize: false,
    percentage: 97,
    stats: { conversions: "9.5%", participants: "220k", difficulty: "★☆☆" },
    chartData: [50, 70, 85, 93, 97]
  },
  {
    id: "q21",
    title: "全球百科大视野国际通用通识竞赛",
    type: "知识答题",
    style: "简约",
    scene: "荣誉证书",
    hot: 19500,
    time: "2026-05-11",
    colorBg: "from-[#F8FAFC] via-[#F1F5F9] to-[#475569]",
    tagText: "开拓视界 笃行千里",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.5%", participants: "38k", difficulty: "★★★" },
    chartData: [20, 40, 60, 75, 86]
  },
  {
    id: "q22",
    title: "英语高考核心词汇防遗忘打卡挑战营",
    type: "每日一答",
    style: "简约",
    scene: "每日打卡",
    hot: 39800,
    time: "2026-05-24",
    colorBg: "from-[#111827] via-[#1E1B4B] to-[#7E22CE]",
    tagText: "词汇狂突 无畏高考",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "7.2%", participants: "131k", difficulty: "★★☆" },
    chartData: [35, 55, 78, 88, 95]
  },
  {
    id: "q23",
    title: "理财基础常识早班车七天打卡大奖",
    type: "每日一答",
    style: "商务",
    scene: "每日打卡",
    hot: 24700,
    time: "2026-05-14",
    colorBg: "from-[#FFF7ED] via-[#FFEDD5] to-[#D97706]",
    tagText: "理财先人一步 赢取好礼",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.8%", participants: "62k", difficulty: "★☆☆" },
    chartData: [30, 45, 68, 82, 90]
  },
  {
    id: "q24",
    title: "健康科普膳食营养每日一记小答题",
    type: "每日一答",
    style: "可爱",
    scene: "每日打卡",
    hot: 34100,
    time: "2026-05-22",
    colorBg: "from-[#EEF2F6] via-[#E2E8F0] to-[#10B981]",
    tagText: "膳食平衡 吃出健康",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.2%", participants: "89k", difficulty: "★☆☆" },
    chartData: [40, 58, 75, 86, 93]
  },
  {
    id: "q25",
    title: "新媒体时事热点分析每日极速微训",
    type: "每日一答",
    style: "简约",
    scene: "每日打卡",
    hot: 28900,
    time: "2026-05-16",
    colorBg: "from-[#ECE9E6] to-[#6366F1]",
    tagText: "热点雷达 迅速捕捉",
    hasPrize: true,
    percentage: 91,
    stats: { conversions: "5.1%", participants: "74k", difficulty: "★★☆" },
    chartData: [25, 48, 70, 85, 91]
  },
  {
    id: "q26",
    title: "保密安全守护神条例每日精炼比拼",
    type: "每日一答",
    style: "商务",
    scene: "每日打卡",
    hot: 48900,
    time: "2026-05-24",
    colorBg: "from-[#111827] via-[#311042] to-[#B91C1C]",
    tagText: "严守底线 保密防谍",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "8.4%", participants: "192k", difficulty: "★★☆" },
    chartData: [40, 60, 80, 92, 98]
  },
  {
    id: "q27",
    title: "智育美育融合手工知识每日小问案",
    type: "每日一答",
    style: "卡通",
    scene: "每日打卡",
    hot: 31500,
    time: "2026-05-20",
    colorBg: "from-[#FCE7F3] via-[#F472B6] to-[#DB2777]",
    tagText: "手脑并用 创造未来",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "5.2%", participants: "81k", difficulty: "★☆☆" },
    chartData: [35, 52, 70, 84, 92]
  },
  {
    id: "q28",
    title: "法治普法民法典要点普及每日打卡",
    type: "每日一答",
    style: "简约",
    scene: "每日打卡",
    hot: 36200,
    time: "2026-05-22",
    colorBg: "from-[#ECFDF5] via-[#D1FAE5] to-[#047857]",
    tagText: "法治同行 律己爱港",
    hasPrize: false,
    percentage: 94,
    stats: { conversions: "6.0%", participants: "105k", difficulty: "★☆☆" },
    chartData: [30, 55, 75, 88, 94]
  },
  {
    id: "q29",
    title: "小学语文成语大比拼每日点滴晨读",
    type: "每日一答",
    style: "国潮",
    scene: "每日打卡",
    hot: 42300,
    time: "2026-05-26",
    colorBg: "from-[#FAF7F2] to-[#D97706]",
    tagText: "积少成多 提笔成章",
    hasPrize: true,
    percentage: 97,
    stats: { conversions: "7.9%", participants: "142k", difficulty: "★☆☆" },
    chartData: [40, 62, 81, 93, 97]
  },
  {
    id: "q30",
    title: "职场效率达人高效工作法每日精选",
    type: "每日一答",
    style: "商务",
    scene: "每日打卡",
    hot: 21550,
    time: "2026-05-13",
    colorBg: "from-[#F8FAFC] via-[#64748B] to-[#1E293B]",
    tagText: "告别拖延 效能爆棚",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.9%", participants: "49k", difficulty: "★★☆" },
    chartData: [25, 45, 62, 78, 86]
  },
  {
    id: "q31",
    title: "安全出行规规章递进关卡全能通",
    type: "闯关答题",
    style: "卡通",
    scene: "趣味裂变",
    hot: 49800,
    time: "2026-05-10",
    colorBg: "from-[#FFF1F2] via-[#FDA4AF] to-[#EF4444]",
    tagText: "全关攻克 拒绝违章",
    hasPrize: true,
    percentage: 99,
    stats: { conversions: "9.8%", participants: "235k", difficulty: "★★★" },
    chartData: [45, 65, 83, 95, 99]
  },
  {
    id: "q32",
    title: "中华璀璨诗词十阶攀升极速闯关",
    type: "闯关答题",
    style: "国潮",
    scene: "荣誉证书",
    hot: 45100,
    time: "2026-05-27",
    colorBg: "from-[#FDF2F8] via-[#FCE7F3] to-[#C084FC]",
    tagText: "登顶诗王 领衔荣誉",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "8.5%", participants: "172k", difficulty: "★★☆" },
    chartData: [35, 58, 78, 90, 96]
  },
  {
    id: "q33",
    title: "常识大比拼智慧生命线极限闯境",
    type: "闯关答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 38200,
    time: "2026-05-19",
    colorBg: "from-[#0F172A] via-[#1E1B4B] to-[#4F46E5]",
    tagText: "生活百科 智者突围",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "5.7%", participants: "91k", difficulty: "★★☆" },
    chartData: [30, 52, 72, 87, 93]
  },
  {
    id: "q34",
    title: "金融理财通识神卡递进通关大挑战",
    type: "闯关答题",
    style: "商务",
    scene: "附带解析",
    hot: 29500,
    time: "2026-05-12",
    colorBg: "from-[#022C22] via-[#0D9488] to-[#047857]",
    tagText: "智慧理财 避开巨坑",
    hasPrize: true,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "64k", difficulty: "★★★" },
    chartData: [30, 48, 68, 80, 91]
  },
  {
    id: "q35",
    title: "小学成语高手递阶成神冲关榜赛",
    type: "闯关答题",
    style: "卡通",
    scene: "荣誉证书",
    hot: 34200,
    time: "2026-05-11",
    colorBg: "from-[#FAF5FF] via-[#F3E8FF] to-[#A855F7]",
    tagText: "妙笔生花 快节奏冲级",
    hasPrize: true,
    percentage: 94,
    stats: { conversions: "6.1%", participants: "88k", difficulty: "★★☆" },
    chartData: [40, 55, 75, 87, 94]
  },
  {
    id: "q36",
    title: "世界历史轴线探秘极限闯关对决",
    type: "闯关答题",
    style: "简约",
    scene: "附带解析",
    hot: 28400,
    time: "2026-05-15",
    colorBg: "from-[#111827] via-[#1E293B] to-[#475569]",
    tagText: "古今纵横 连克雄关",
    hasPrize: false,
    percentage: 89,
    stats: { conversions: "4.3%", participants: "49k", difficulty: "★★★" },
    chartData: [20, 45, 62, 78, 89]
  },
  {
    id: "q37",
    title: "智慧城市低碳分类多关卡趣味通",
    type: "闯关答题",
    style: "可爱",
    scene: "趣味裂变",
    hot: 31200,
    time: "2026-05-09",
    colorBg: "from-[#F0FDFA] via-[#CCFBF1] to-[#14B8A6]",
    tagText: "环保先锋 极致全破",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.4%", participants: "72k", difficulty: "★☆☆" },
    chartData: [35, 55, 78, 88, 95]
  },
  {
    id: "q38",
    title: "消防器械操作标准递阶闯关赛",
    type: "闯关答题",
    style: "商务",
    scene: "荣誉证书",
    hot: 22100,
    time: "2026-05-06",
    colorBg: "from-[#7F1D1D] via-[#B91C1C] to-[#EF4444]",
    tagText: "实战规范 一关一得",
    hasPrize: true,
    percentage: 87,
    stats: { conversions: "3.2%", participants: "34k", difficulty: "★★★" },
    chartData: [25, 40, 60, 78, 87]
  },
  {
    id: "q39",
    title: "全能生存法则危机灾害大冲关",
    type: "闯关答题",
    style: "简约",
    scene: "附带解析",
    hot: 27500,
    time: "2026-05-02",
    colorBg: "from-[#1E3A8A] via-[#0F172A] to-[#0D9488]",
    tagText: "求生法则 极限求真",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "4.7%", participants: "59k", difficulty: "★★☆" },
    chartData: [30, 50, 70, 83, 91]
  },
  {
    id: "q40",
    title: "实时全速脑力匹配双人在线对决",
    type: "PK答题",
    style: "科技",
    scene: "趣味裂变",
    hot: 67100,
    time: "2026-05-25",
    colorBg: "from-[#0F172A] via-[#1E1B4B] to-[#7C3AED]",
    tagText: "极速秒配 智力炸裂",
    hasPrize: true,
    percentage: 99,
    stats: { conversions: "11.1%", participants: "420k", difficulty: "★★★" },
    chartData: [50, 75, 90, 97, 99]
  },
  {
    id: "q41",
    title: "智勇双星团队混战天梯突围赛",
    type: "PK答题",
    style: "青春",
    scene: "趣味裂变",
    hot: 48900,
    time: "2026-05-23",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#2563EB]",
    tagText: "并肩作战 捍卫荣耀",
    hasPrize: true,
    percentage: 97,
    stats: { conversions: "8.2%", participants: "192k", difficulty: "★★☆" },
    chartData: [40, 60, 80, 93, 97]
  },
  {
    id: "q42",
    title: "默契好友局同城同题趣味速PK",
    type: "PK答题",
    style: "可爱",
    scene: "趣味裂变",
    hot: 35600,
    time: "2026-05-20",
    colorBg: "from-[#FFF5F5] via-[#FED7D7] to-[#F43F5E]",
    tagText: "好友相约 爆笑PK",
    hasPrize: false,
    percentage: 94,
    stats: { conversions: "6.9%", participants: "91k", difficulty: "★☆☆" },
    chartData: [35, 55, 75, 88, 94]
  },
  {
    id: "q43",
    title: "高考高频知识点极智竞速擂台PK",
    type: "PK答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 42100,
    time: "2026-05-18",
    colorBg: "from-[#450A0A] via-[#581C87] to-[#8B5CF6]",
    tagText: "考点速记 越配越勇",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "7.1%", participants: "128k", difficulty: "★★★" },
    chartData: [40, 62, 80, 91, 96]
  },
  {
    id: "q44",
    title: "安全常识红蓝段位排位挑战局",
    type: "PK答题",
    style: "商务",
    scene: "企业级",
    hot: 29800,
    time: "2026-05-14",
    colorBg: "from-[#F8FAFC] via-[#64748B] to-[#0284C7]",
    tagText: "以赛促学 强强对局",
    hasPrize: true,
    percentage: 91,
    stats: { conversions: "4.8%", participants: "64k", difficulty: "★★☆" },
    chartData: [30, 50, 72, 85, 91]
  },
  {
    id: "q45",
    title: "大英词汇极智抢答三人PK夺宝",
    type: "PK答题",
    style: "青春",
    scene: "趣味裂变",
    hot: 38200,
    time: "2026-05-10",
    colorBg: "from-[#F0FDF4] via-[#DCFCE7] to-[#10B981]",
    tagText: "背词对战 乐趣无限",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "6.3%", participants: "94k", difficulty: "★★☆" },
    chartData: [35, 55, 78, 88, 95]
  },
  {
    id: "q46",
    title: "唐诗宋词连环对局古典派实时PK",
    type: "PK答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 34100,
    time: "2026-05-08",
    colorBg: "from-[#FEF2F2] via-[#FEE2E2] to-[#B91C1C]",
    tagText: "骚人墨客 笔墨决雌雄",
    hasPrize: false,
    percentage: 92,
    stats: { conversions: "5.5%", participants: "71k", difficulty: "★★☆" },
    chartData: [25, 48, 70, 85, 92]
  },
  {
    id: "q47",
    title: "百科全书乱斗版百人群雄大逃杀",
    type: "PK答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 54100,
    time: "2026-05-01",
    colorBg: "from-[#111827] via-[#1E293B] to-[#D97706]",
    tagText: "百人百题 生存到最后",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "9.2%", participants: "260k", difficulty: "★★★" },
    chartData: [50, 70, 85, 94, 98]
  },
  {
    id: "q48",
    title: "少儿算术极限心算速度大激斗",
    type: "PK答题",
    style: "卡通",
    scene: "荣誉证书",
    hot: 29500,
    time: "2026-04-28",
    colorBg: "from-[#FDF4FF] via-[#E9D5FF] to-[#A855F7]",
    tagText: "算术拼配 风驰电掣",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.5%", participants: "55k", difficulty: "★★☆" },
    chartData: [30, 50, 68, 82, 90]
  },
  {
    id: "q49",
    title: "违章驾驶交通监控违规看片答题",
    type: "视频答题",
    style: "简约",
    scene: "附带解析",
    hot: 22100,
    time: "2026-05-18",
    colorBg: "from-[#0F172A] via-[#1E1B4B] to-[#7F1D1D]",
    tagText: "规范操作 规避违章",
    hasPrize: true,
    percentage: 89,
    stats: { conversions: "4.1%", participants: "41k", difficulty: "★★☆" },
    chartData: [25, 45, 62, 78, 89]
  },
  {
    id: "q50",
    title: "建筑施工高空作业滑坠看片纠错",
    type: "视频答题",
    style: "商务",
    scene: "企业级",
    hot: 19500,
    time: "2026-05-14",
    colorBg: "from-[#F8FAFC] via-[#64748B] to-[#1E3A8A]",
    tagText: "看图纠违 安全第十",
    hasPrize: true,
    percentage: 87,
    stats: { conversions: "3.2%", participants: "32k", difficulty: "★★★" },
    chartData: [20, 40, 58, 75, 87]
  },
  {
    id: "q51",
    title: "商务外事礼仪及沟通名场面视听选择",
    type: "视频答题",
    style: "商务",
    scene: "企业级",
    hot: 28400,
    time: "2026-05-20",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#475569]",
    tagText: "优雅得体 沉浸交互",
    hasPrize: false,
    percentage: 94,
    stats: { conversions: "5.4%", participants: "59k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 85, 94]
  },
  {
    id: "q52",
    title: "大英情景会话完美视听结合大精炼",
    type: "视频答题",
    style: "青春",
    scene: "附带解析",
    hot: 39500,
    time: "2026-05-23",
    colorBg: "from-[#F5F5F7] via-[#E4E4E7] to-[#10B981]",
    tagText: "看片听音 学纯正英语",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "7.1%", participants: "115k", difficulty: "★★☆" },
    chartData: [45, 60, 78, 89, 96]
  },
  {
    id: "q53",
    title: "公共场所防踩踏事件求生技能视听",
    type: "视频答题",
    style: "简约",
    scene: "附带解析",
    hot: 31250,
    time: "2026-05-19",
    colorBg: "from-[#FFF7ED] via-[#FFEDD5] to-[#EF4444]",
    tagText: "科学避险 生死一瞬",
    hasPrize: false,
    percentage: 92,
    stats: { conversions: "5.1%", participants: "78k", difficulty: "★★☆" },
    chartData: [30, 48, 68, 82, 92]
  },
  {
    id: "q54",
    title: "家庭防盗防非金融诈骗情景视频选答",
    type: "视频答题",
    style: "可爱",
    scene: "趣味裂变",
    hot: 45600,
    time: "2026-05-25",
    colorBg: "from-[#FFFBEB] via-[#FEF3C7] to-[#D97706]",
    tagText: "擦亮双眸 捂紧钱袋",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "8.5%", participants: "154k", difficulty: "★☆☆" },
    chartData: [40, 60, 80, 91, 98]
  },
  {
    id: "q55",
    title: "微电影中看传统非遗技艺辨识问答",
    type: "视频答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 28400,
    time: "2026-05-11",
    colorBg: "from-[#FAF7F2] to-[#4F46E5]",
    tagText: "匠心传承 看片识珍",
    hasPrize: false,
    percentage: 90,
    stats: { conversions: "4.7%", participants: "61k", difficulty: "★☆☆" },
    chartData: [30, 48, 65, 80, 90]
  },
  {
    id: "q56",
    title: "AI核心技术发展史全景视听趣味问",
    type: "视频答题",
    style: "科技",
    scene: "荣誉证书",
    hot: 39100,
    time: "2026-05-21",
    colorBg: "from-[#0F172A] via-[#1E3A8A] to-[#0D9488]",
    tagText: "科技浪潮 边看边答",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "6.9%", participants: "108k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 88, 95]
  },
  {
    id: "q57",
    title: "森林防火现场救灾错误视频演练",
    type: "视频答题",
    style: "简约",
    scene: "附带解析",
    hot: 24500,
    time: "2026-05-10",
    colorBg: "from-[#7F1D1D] via-[#B91C1C] to-[#F97316]",
    tagText: "火场绝境 规范演练",
    hasPrize: true,
    percentage: 88,
    stats: { conversions: "3.8%", participants: "45k", difficulty: "★★★" },
    chartData: [20, 42, 60, 78, 88]
  },
  {
    id: "q58",
    title: "测试你隐藏的霍格沃茨学派精神人格",
    type: "趣味答题",
    style: "卡通",
    scene: "趣味裂变",
    hot: 62050,
    time: "2026-05-24",
    colorBg: "from-[#111827] via-[#581C87] to-[#EC4899]",
    tagText: "魔法召唤 奇幻揭晓",
    hasPrize: true,
    percentage: 99,
    stats: { conversions: "10.4%", participants: "380k", difficulty: "★☆☆" },
    chartData: [50, 70, 85, 95, 99]
  },
  {
    id: "q59",
    title: "你的双脑年龄与未来三年财富大解锁",
    type: "趣味答题",
    style: "可爱",
    scene: "趣味裂变",
    hot: 55200,
    time: "2026-05-21",
    colorBg: "from-[#FAF5FF] via-[#E9D5FF] to-[#DB2777]",
    tagText: "潜能分析 财源密码",
    hasPrize: false,
    percentage: 98,
    stats: { conversions: "9.1%", participants: "290k", difficulty: "★☆☆" },
    chartData: [40, 60, 80, 92, 98]
  },
  {
    id: "q60",
    title: "测测你在中国经典文学代表神仙体魄",
    type: "趣味答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 49400,
    time: "2026-05-25",
    colorBg: "from-[#450A0A] via-[#7F1D1D] to-[#ea580c]",
    tagText: "仙风道骨 八字神韵",
    hasPrize: true,
    percentage: 97,
    stats: { conversions: "8.4%", participants: "198k", difficulty: "★☆☆" },
    chartData: [35, 58, 80, 90, 97]
  },
  {
    id: "q61",
    title: "朋友圈爆款职场情商与领导力趣味评估",
    type: "趣味答题",
    style: "商务",
    scene: "趣味裂变",
    hot: 39800,
    time: "2026-05-18",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#475569]",
    tagText: "社交段位 一测便知",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "7.1%", participants: "125k", difficulty: "★★☆" },
    chartData: [30, 52, 75, 87, 95]
  },
  {
    id: "q62",
    title: "穿梭古代测你最契合宋朝何种神仙地位",
    type: "趣味答题",
    style: "国潮",
    scene: "趣味裂变",
    hot: 41200,
    time: "2026-05-16",
    colorBg: "from-[#FAF7F2] to-[#B91C1C]",
    tagText: "梦回宋明 一览江山",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.5%", participants: "110k", difficulty: "★☆☆" },
    chartData: [40, 60, 78, 88, 93]
  },
  {
    id: "q63",
    title: "测你的日常金钱观及未来富豪成长指数",
    type: "趣味答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 31200,
    time: "2026-05-12",
    colorBg: "from-[#E0F2FE] via-[#BAE6FD] to-[#0284C7]",
    tagText: "财商觉醒 逆境发财",
    hasPrize: true,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "78k", difficulty: "★☆☆" },
    chartData: [25, 45, 68, 82, 91]
  },
  {
    id: "q64",
    title: "潜情绪负荷与都市减压奇葩指南自估",
    type: "趣味答题",
    style: "可爱",
    scene: "趣味裂变",
    hot: 28400,
    time: "2026-05-10",
    colorBg: "from-[#ECFDF5] via-[#A7F3D0] to-[#10B981]",
    tagText: "心灵SPA 解压指南",
    hasPrize: false,
    percentage: 90,
    stats: { conversions: "4.2%", participants: "59k", difficulty: "★☆☆" },
    chartData: [30, 50, 70, 81, 90]
  },
  {
    id: "q65",
    title: "测测你是哪种神奇保护动物奇妙性格",
    type: "趣味答题",
    style: "卡通",
    scene: "趣味裂变",
    hot: 43200,
    time: "2026-05-22",
    colorBg: "from-[#FEF3C7] via-[#FDE68A] to-[#F59E0B]",
    tagText: "灵魂图腾 萌化朋友圈",
    hasPrize: true,
    percentage: 96,
    stats: { conversions: "8.1%", participants: "145k", difficulty: "★☆☆" },
    chartData: [35, 58, 78, 89, 96]
  },
  {
    id: "q66",
    title: "MBTI全新职业契合度进阶版深度破译",
    type: "趣味答题",
    style: "简约",
    scene: "趣味裂变",
    hot: 51200,
    time: "2026-05-26",
    colorBg: "from-[#F3F4F6] via-[#D1D5DB] to-[#1E293B]",
    tagText: "真我密码 职业领航",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "9.3%", participants: "215k", difficulty: "★★☆" },
    chartData: [45, 65, 83, 93, 98]
  },
  {
    id: "q67",
    title: "新员工企业文化政策红线考核指南",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 31200,
    time: "2026-05-24",
    colorBg: "from-[#F8FAFC] via-[#E2E8F0] to-[#1E3A8A]",
    tagText: "以学带答 规避雷区",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.8%", participants: "74k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 88, 95]
  },
  {
    id: "q68",
    title: "财务安全法规宣贯与极简解析伴读",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 24700,
    time: "2026-05-18",
    colorBg: "from-[#FFF7ED] via-[#FFEDD5] to-[#475569]",
    tagText: "账目清爽 合规无阻",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "51k", difficulty: "★★☆" },
    chartData: [30, 48, 68, 81, 91]
  },
  {
    id: "q69",
    title: "大英四六级高分阅读突围逐篇演练",
    type: "学习答题",
    style: "简约",
    scene: "附带解析",
    hot: 42100,
    time: "2026-05-25",
    colorBg: "from-[#EEF2F6] via-[#E2E8F0] to-[#4F46E5]",
    tagText: "真题解析 高频提速",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "7.9%", participants: "154k", difficulty: "★★☆" },
    chartData: [40, 62, 81, 92, 98]
  },
  {
    id: "q70",
    title: "管理学杰出战略高频原理速成大课堂",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 29800,
    time: "2026-05-17",
    colorBg: "from-[#F1F5F9] via-[#E2E8F0] to-[#0284C7]",
    tagText: "大局观 领袖战略速成",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "5.1%", participants: "82k", difficulty: "★★☆" },
    chartData: [30, 50, 70, 83, 92]
  },
  {
    id: "q71",
    title: "国家新颁布保密安全法条精讲解读营",
    type: "学习答题",
    style: "简约",
    scene: "附带解析",
    hot: 35600,
    time: "2026-05-15",
    colorBg: "from-[#7F1D1D] via-[#B91C1C] to-[#475569]",
    tagText: "普法利器 深入人心",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.2%", participants: "108k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 86, 93]
  },
  {
    id: "q72",
    title: "全景销售实战话术避坑指引精炼大练",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 19500,
    time: "2026-05-10",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#1E293B]",
    tagText: "破冰话术 签单神速",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.5%", participants: "38k", difficulty: "★★★" },
    chartData: [20, 40, 58, 75, 86]
  },
  {
    id: "q73",
    title: "网络安全红线标准规范以练代学自刷",
    type: "学习答题",
    style: "科技",
    scene: "企业级",
    hot: 28400,
    time: "2026-05-12",
    colorBg: "from-[#0F172A] via-[#1E3A8A] to-[#0D9488]",
    tagText: "筑牢防线 规避泄密",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.7%", participants: "61k", difficulty: "★★☆" },
    chartData: [30, 48, 68, 81, 90]
  },
  {
    id: "q74",
    title: "民法典居民日常法常识趣味测试普及",
    type: "学习答题",
    style: "简约",
    scene: "附带解析",
    hot: 39100,
    time: "2026-05-22",
    colorBg: "from-[#ECFDF5] via-[#A7F3D0] to-[#047857]",
    tagText: "全民护法 和谐民生",
    hasPrize: false,
    percentage: 94,
    stats: { conversions: "6.8%", participants: "115k", difficulty: "★☆☆" },
    chartData: [40, 60, 78, 88, 94]
  },
  {
    id: "q75",
    title: "新员工入职手册核心条文极简指引学",
    type: "学习答题",
    style: "商务",
    scene: "企业级",
    hot: 21550,
    time: "2026-05-09",
    colorBg: "from-[#FAF5FF] via-[#D1D5DB] to-[#1E1B4B]",
    tagText: "文化融入 快速通关",
    hasPrize: true,
    percentage: 87,
    stats: { conversions: "3.8%", participants: "45k", difficulty: "★☆☆" },
    chartData: [25, 45, 62, 78, 87]
  },
  {
    id: "q76",
    title: "科目一驾考无忧全真模拟智能错题刷",
    type: "练习",
    style: "简约",
    scene: "附带解析",
    hot: 31200,
    time: "2026-05-24",
    colorBg: "from-[#E0F2FE] via-[#BAE6FD] to-[#0254C7]",
    tagText: "秒刷错题 一次通关",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.8%", participants: "78k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 88, 95]
  },
  {
    id: "q77",
    title: "公务员国考省考常识专项智能模拟题",
    type: "练习",
    style: "简约",
    scene: "附带解析",
    hot: 24700,
    time: "2026-05-18",
    colorBg: "from-[#F8FAFC] via-[#E2E8F0] to-[#475569]",
    tagText: "热点攻坚 行测神功",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "59k", difficulty: "★★★" },
    chartData: [30, 48, 68, 81, 91]
  },
  {
    id: "q78",
    title: "计算机二级Office考试高频选择复刷",
    type: "练习",
    style: "科技",
    scene: "附带解析",
    hot: 42100,
    time: "2026-05-25",
    colorBg: "from-[#111827] via-[#1E1B4B] to-[#311042]",
    tagText: "熟能生巧 实操提分",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "7.9%", participants: "135k", difficulty: "★★☆" },
    chartData: [40, 62, 81, 92, 98]
  },
  {
    id: "q79",
    title: "安全操作规章常态化周练自学题库练",
    type: "练习",
    style: "商务",
    scene: "附带解析",
    hot: 29800,
    time: "2026-05-17",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#1E293B]",
    tagText: "筑牢防线 日日筑魂",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "5.1%", participants: "81k", difficulty: "★★☆" },
    chartData: [30, 50, 70, 83, 92]
  },
  {
    id: "q80",
    title: "高中化学元素周期表必考要点自刷册",
    type: "练习",
    style: "卡通",
    scene: "附带解析",
    hot: 35600,
    time: "2026-05-15",
    colorBg: "from-[#FDF2F8] via-[#FCE7F3] to-[#F472B6]",
    tagText: "配平反应 基础夯实",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.2%", participants: "92k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 86, 93]
  },
  {
    id: "q81",
    title: "大英核心语法精细打磨错题特训营版",
    type: "练习",
    style: "简约",
    scene: "附带解析",
    hot: 19500,
    time: "2026-05-10",
    colorBg: "from-[#FAF5FF] via-[#F3E8FF] to-[#D946EF]",
    tagText: "时态语态 系统理顺",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.5%", participants: "34k", difficulty: "★★☆" },
    chartData: [20, 40, 58, 75, 86]
  },
  {
    id: "q82",
    title: "中考物理运动学必考综合纠错本大刷",
    type: "练习",
    style: "简约",
    scene: "附带解析",
    hot: 28400,
    time: "2026-05-12",
    colorBg: "from-[#F3F4F6] via-[#E5E7EB] to-[#4F46E5]",
    tagText: "速度变合 攻克物理",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.7%", participants: "55k", difficulty: "★★★" },
    chartData: [30, 48, 68, 81, 90]
  },
  {
    id: "q83",
    title: "安全生产常识高频复习周检模拟系统",
    type: "练习",
    style: "商务",
    scene: "附带解析",
    hot: 39100,
    time: "2026-05-22",
    colorBg: "from-[#FFF7ED] via-[#FFEDD5] to-[#EF4444]",
    tagText: "以练筑墙 健康你我",
    hasPrize: false,
    percentage: 94,
    stats: { conversions: "6.8%", participants: "108k", difficulty: "★★☆" },
    chartData: [40, 60, 78, 88, 94]
  },
  {
    id: "q84",
    title: "精益六西格玛核心绿带错题速查训练",
    type: "练习",
    style: "科技",
    scene: "附带解析",
    hot: 21550,
    time: "2026-05-09",
    colorBg: "from-[#E0F2FE] via-[#0D9488] to-[#047857]",
    tagText: "持续改善 攻克质量",
    hasPrize: true,
    percentage: 87,
    stats: { conversions: "3.8%", participants: "41k", difficulty: "★★★" },
    chartData: [25, 45, 62, 78, 87]
  },
  {
    id: "q85",
    title: "消防安全责任制度秋季实名严肃考试",
    type: "考试",
    style: "商务",
    scene: "防作弊",
    hot: 31200,
    time: "2026-05-24",
    colorBg: "from-[#7F1D1D] via-[#B91C1C] to-[#ea580c]",
    tagText: "责任在肩 严防舞弊",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.8%", participants: "71k", difficulty: "★★★" },
    chartData: [35, 55, 75, 88, 95]
  },
  {
    id: "q86",
    title: "国家数字安全红线网络法条深度质检",
    type: "考试",
    style: "商务",
    scene: "防作弊",
    hot: 24700,
    time: "2026-05-18",
    colorBg: "from-[#F8FAFC] via-[#64748B] to-[#1E293B]",
    tagText: "红线守护 实名大考",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "52k", difficulty: "★★★" },
    chartData: [30, 48, 68, 81, 91]
  },
  {
    id: "q87",
    title: "中层领导核心管理胜任力闭卷严肃考",
    type: "考试",
    style: "商务",
    scene: "防作弊",
    hot: 42100,
    time: "2026-05-25",
    colorBg: "from-[#EFF6FF] via-[#DBEAFE] to-[#1E3A8A]",
    tagText: "将帅之帅 实名认证",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "7.9%", participants: "125k", difficulty: "★★★" },
    chartData: [40, 62, 81, 92, 98]
  },
  {
    id: "q88",
    title: "反洗钱与外汇合规操作高规格实考场",
    type: "考试",
    style: "商务",
    scene: "防作弊",
    hot: 29800,
    time: "2026-05-17",
    colorBg: "from-[#FFF1F2] via-[#FDA4AF] to-[#B91C1C]",
    tagText: "规避风险 严肃合规",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "5.1%", participants: "69k", difficulty: "★★★" },
    chartData: [30, 50, 70, 83, 92]
  },
  {
    id: "q89",
    title: "医疗器械合规与防人情舞弊大考全系统",
    type: "考试",
    style: "商业",
    scene: "防作弊",
    hot: 35600,
    time: "2026-05-15",
    colorBg: "from-[#F1F5F9] via-[#E2E8F0] to-[#5C21B6]",
    tagText: "公平公正 严肃大考",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.2%", participants: "89k", difficulty: "★★★" },
    chartData: [35, 55, 75, 86, 93]
  },
  {
    id: "q90",
    title: "特种设备带电作业特工证书严防考试",
    type: "考试",
    style: "科技",
    scene: "荣誉证书",
    hot: 19500,
    time: "2026-05-10",
    colorBg: "from-[#111827] via-[#1E1B4B] to-[#0D9488]",
    tagText: "持证上岗 火力全开",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.5%", participants: "31k", difficulty: "★★★" },
    chartData: [20, 40, 58, 75, 86]
  },
  {
    id: "q91",
    title: "民事诉讼法最新司法解释全国严肃考",
    type: "考试",
    style: "简约",
    scene: "防作弊",
    hot: 28400,
    time: "2026-05-12",
    colorBg: "from-[#FAF5FF] via-[#F3E8FF] to-[#047857]",
    tagText: "以法之名 司法威严",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.7%", participants: "54k", difficulty: "★★★" },
    chartData: [30, 48, 68, 81, 90]
  },
  {
    id: "q92",
    title: "卓越项目总监特训闭卷认证年度大考",
    type: "考试",
    style: "商务",
    scene: "荣誉证书",
    hot: 39100,
    time: "2026-05-22",
    colorBg: "from-[#FFFFFF] to-[#3B82F6]",
    tagText: "项目管家 权威结业",
    hasPrize: true,
    percentage: 94,
    stats: { conversions: "6.8%", participants: "105k", difficulty: "★★★" },
    chartData: [40, 60, 78, 88, 94]
  },
  {
    id: "q93",
    title: "小白理财投资实战微课随课结题伴伴学",
    type: "课程",
    style: "简约",
    scene: "荣誉证书",
    hot: 31200,
    time: "2026-05-24",
    colorBg: "from-[#FDF2F8] via-[#FCE7F3] to-[#D946EF]",
    tagText: "精细带课 轻松起步",
    hasPrize: true,
    percentage: 95,
    stats: { conversions: "5.8%", participants: "72k", difficulty: "★☆☆" },
    chartData: [35, 55, 75, 88, 95]
  },
  {
    id: "q94",
    title: "Python零基础数据抓取与AI应用微课",
    type: "课程",
    style: "科技",
    scene: "企级业",
    hot: 24700,
    time: "2026-05-18",
    colorBg: "from-[#0F172A] via-[#1E3A8A] to-[#0D9488]",
    tagText: "实操进阶 边听边测",
    hasPrize: false,
    percentage: 91,
    stats: { conversions: "4.9%", participants: "55k", difficulty: "★★☆" },
    chartData: [30, 48, 68, 81, 91]
  },
  {
    id: "q95",
    title: "Axure高保真交互设计系统性提升精讲",
    type: "课程",
    style: "简约",
    scene: "企业级",
    hot: 42100,
    time: "2026-05-25",
    colorBg: "from-[#FAF7F2] to-[#B91C1C]",
    tagText: "原型之神 有声指导",
    hasPrize: true,
    percentage: 98,
    stats: { conversions: "7.9%", participants: "115k", difficulty: "★★☆" },
    chartData: [40, 62, 81, 92, 98]
  },
  {
    id: "q96",
    title: "短视频爆款脚本设计及画面运镜系统",
    type: "课程",
    style: "青春",
    scene: "荣誉证书",
    hot: 29800,
    time: "2026-05-17",
    colorBg: "from-[#FFF5F5] via-[#FED7D7] to-[#F43F5E]",
    tagText: "爆款逻辑 运镜之巅",
    hasPrize: true,
    percentage: 92,
    stats: { conversions: "5.1%", participants: "74k", difficulty: "★★☆" },
    chartData: [30, 50, 70, 83, 92]
  },
  {
    id: "q97",
    title: "AI大模型核心概念与行业落地全景课",
    type: "课程",
    style: "科技",
    scene: "企业级",
    hot: 35600,
    time: "2026-05-15",
    colorBg: "from-[#111827] via-[#5C21B6] to-[#4F46E5]",
    tagText: "大模型前沿 指引实操",
    hasPrize: false,
    percentage: 93,
    stats: { conversions: "6.2%", participants: "91k", difficulty: "★★☆" },
    chartData: [35, 55, 75, 86, 93]
  },
  {
    id: "q98",
    title: "项目管理PMP高频重难点全套权威视频",
    type: "课程",
    style: "商务",
    scene: "荣誉证书",
    hot: 19500,
    time: "2026-05-10",
    colorBg: "from-[#F8FAFC] via-[#64748B] to-[#475569]",
    tagText: "项目操盘手 系统强化",
    hasPrize: true,
    percentage: 86,
    stats: { conversions: "3.5%", participants: "34k", difficulty: "★★★" },
    chartData: [20, 40, 58, 75, 86]
  },
  {
    id: "q99",
    title: "深度学习前沿算法复现实操微课班",
    type: "课程",
    style: "科技",
    scene: "企业级",
    hot: 28400,
    time: "2026-05-12",
    colorBg: "from-[#ECE9E6] to-[#047857]",
    tagText: "公式推导 编程落地",
    hasPrize: true,
    percentage: 90,
    stats: { conversions: "4.7%", participants: "51k", difficulty: "★★★" },
    chartData: [30, 48, 68, 81, 90]
  },
  {
    id: "q100",
    title: "小白新媒体爆款运营精髓突围陪伴营",
    type: "课程",
    style: "可爱",
    scene: "荣誉证书",
    hot: 39100,
    time: "2026-05-22",
    colorBg: "from-[#EEFFD4] via-[#D1FAE5] to-[#10B981]",
    tagText: "零基引流 极致曝光",
    hasPrize: true,
    percentage: 94,
    stats: { conversions: "6.8%", participants: "98k", difficulty: "★☆☆" },
    chartData: [40, 60, 78, 88, 94]
  }
];

export const CALENDAR_NODES = [
  {
    id: "exam_p1",
    month: "6月",
    day: "07",
    title: "高考百科大冲关",
    gameName: "高考百科大PK",
    tag: "考前热点 🎯",
    bgClass: "from-rose-50/90 to-white hover:to-rose-50/20 border-pink-100/80 hover:border-pink-300 hover:shadow-[0_12px_24px_rgba(244,63,94,0.12)]",
    textClass: "text-pink-600 bg-pink-100/70",
    headerBg: "bg-gradient-to-r from-pink-500 to-rose-500",
    btnClass: "bg-pink-500 hover:bg-pink-600 shadow-md shadow-pink-100 hover:shadow-pink-300/50",
    gameId: "q1",
    decor: "🎓📝",
    hotPill: "🔥 转化：+98%",
    status: "大促热推中"
  },
  {
    id: "exam_p2",
    month: "6月",
    day: "15",
    title: "全国安全生产月大考",
    gameName: "企业安全规章大闯关",
    tag: "合规内训 🛡️",
    bgClass: "from-emerald-50/90 to-white hover:to-emerald-50/20 border-emerald-100/80 hover:border-emerald-300 hover:shadow-[0_12px_24px_rgba(16,185,129,0.12)]",
    textClass: "text-emerald-700 bg-emerald-100/70",
    headerBg: "bg-gradient-to-r from-emerald-600 to-teal-600",
    btnClass: "bg-emerald-600 hover:bg-emerald-700 shadow-md shadow-emerald-100 hover:shadow-emerald-300/50",
    gameId: "q3",
    decor: "🛡️🚨",
    hotPill: "🔥 热度：★★★★★",
    status: "行业高标杆"
  },
  {
    id: "exam_p3",
    month: "7-8月",
    day: "暑",
    title: "暑期趣味心理评测",
    gameName: "神仙体质趣味测评",
    tag: "夏日趣味 ✨",
    bgClass: "from-amber-50/90 to-white hover:to-amber-50/20 border-amber-100/80 hover:border-amber-300 hover:shadow-[0_12px_24px_rgba(245,158,11,0.12)]",
    textClass: "text-amber-700 bg-amber-100/70",
    headerBg: "bg-gradient-to-r from-amber-500 to-orange-500",
    btnClass: "bg-amber-500 hover:bg-amber-600 shadow-md shadow-amber-100 hover:shadow-amber-300/50",
    gameId: "q6",
    decor: "🔮🏄",
    hotPill: "🔥 裂变：+150%",
    status: "热推风向标"
  }
];

export const PLACEHOLDER_PHRASES = [
  "搜索 毕业生高考百科知识大PK",
  "搜索 企业安全生产趣味突击大闯关",
  "搜索 每日英语词汇签到打卡挑战",
  "搜索 趣味性格以及命运体质测评",
  "搜索 新员工入职合规宣贯考试系统",
  "搜索 绿色低碳环保与垃圾分类普及积分赛",
  "搜索 2026年消防与高层防震避险自救评估",
  "搜索 端午屈原传统文化与养生民俗竞答",
  "搜索 全员网络安全与个人防诈骗攻防PK",
  "搜索 职场高情商沟通与谈判技巧极速评测"
];

export const HOT_SEARCHES = [
  { text: "青年五四知识赛", icon: "👮", hot: true },
  { text: "暑期益智词汇打卡", icon: "📝", hot: true },
  { text: "性格神仙体质测评", icon: "🔮", hot: true },
  { text: "消防安全规范考评", icon: "🚨", hot: false },
  { text: "Python基础开发测试", icon: "💻", hot: false },
  { text: "企业半年合规测评", icon: "💎", hot: false }
];

import imgTemplateCover1 from "../../assets/images/marketing_template_cover_1_1779935600707.png";
import imgTemplateCover2 from "../../assets/images/marketing_template_cover_2_1779935619140.png";
import imgTemplateCover3 from "../../assets/images/marketing_template_cover_3_1779935640170.png";

export const getTemplateImage = (id: string, idx = 0) => {
  const images = [imgTemplateCover1, imgTemplateCover2, imgTemplateCover3];
  return images[idx % images.length];
};

export const getTemplateStyle = (id: string) => {
  const stylesMap: Record<string, { bg: string; text: string; border: string }> = {
    q1: { bg: "from-[#eef3fb] to-[#f8faff]", text: "text-blue-700", border: "border-blue-100" },
    q2: { bg: "from-[#fff7ed] to-[#fffdfa]", text: "text-amber-700", border: "border-amber-100" },
    q3: { bg: "from-[#ecf9f4] to-[#f7fdfb]", text: "text-emerald-700", border: "border-emerald-100" },
    q4: { bg: "from-[#fdf1f5] to-[#fef8fa]", text: "text-indigo-700", border: "border-indigo-100" },
    q5: { bg: "from-[#faf1fe] to-[#fdf9ff]", text: "text-purple-700", border: "border-purple-100" },
    q6: { bg: "from-[#ecf9f4] to-[#f7fdfb]", text: "text-teal-700", border: "border-teal-100" },
    q7: { bg: "from-[#f1f5f9] to-[#f8fafc]", text: "text-[#475569]", border: "border-slate-100" },
  };
  return stylesMap[id] || { bg: "from-[#eef3fb] to-[#f8faff]", text: "text-blue-700", border: "border-blue-105" };
};

export const matchSubPlaystyle = (template: any, subPlaystyle: string) => {
  if (subPlaystyle === "全部") return true;
  if (template.title.includes(subPlaystyle) || template.tagText?.includes(subPlaystyle)) return true;
  return false;
};
